name: Selenium NUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # Ensure the correct .NET version is installed

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Restore dependencies
      run: dotnet restore SeleniumNUnit.sln

    - name: Build
      run: dotnet build SeleniumNUnit.sln --configuration Release

    - name: Run tests in headless mode
      run: |
        export PATH=$PATH:/usr/lib/chromium-browser/
        dotnet test SeleniumNUnit.sln --configuration Release --logger "trx;LogFileName=test_results.trx" --test-adapter-path:. --settings HeadlessChrome.settings.json

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_results.trx
