name: Selenium NUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # or the version of .NET you are using

    - name: Restore dependencies
      run: dotnet restore SeleniumNUnit.sln # Specify your solution file here

    - name: Build
      run: dotnet build SeleniumNUnit.sln --configuration Release # Specify your solution file here

    - name: Install Selenium WebDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run tests
      run: dotnet test SeleniumNUnit.sln --configuration Release # Specify your solution file here
